<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * PasajeroHasRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasajeroHasRouteRepository extends EntityRepository
{

    public function findByRoute($routeId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT pasajeroHasRoute
            FROM AppBundle:PasajeroHasRoute pasajeroHasRoute
            WHERE
            pasajeroHasRoute.route = :routeId
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('routeId', $routeId);

        return $query->getResult();
    }

    public function findByRouteAndUser($routeId, $userId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT pasajeroHasRoute, user_
            FROM AppBundle:PasajeroHasRoute pasajeroHasRoute
            INNER JOIN pasajeroHasRoute.user user_
            WHERE
            pasajeroHasRoute.route = :routeId AND
            user_.id = :userId
            ORDER BY pasajeroHasRoute.id DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('routeId', $routeId);
        $query->setParameter('userId', $userId);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

}
