app_route_pasajero_index:
    path:  /
    defaults:
        _controller: AppBundle:RoutePasajero:index
    methods: [GET]

app_route_solicitar_carrera:
    path:  /solicitar-carrera/{id}
    defaults:
        _controller: AppBundle:RoutePasajero:solicitarCarrera
    methods: [GET, POST]

app_route_unsolicitar_carrera:
    path:  /un-solicitar-carrera
    defaults:
        _controller: AppBundle:RoutePasajero:unSolicitarCarrera
    methods: [GET, POST]

app_route_pasajero_view:
    path:  /view
    defaults:
        _controller: AppBundle:RoutePasajero:view
    requirements:
    methods: [POST]

app_route_pasajero_info:
    path:  /info
    defaults:
        _controller: AppBundle:RoutePasajero:info
    requirements:
    methods: [POST]
